INSERT INTO Tags(Name,Description,CreatedDate,UserId) VALUES ('Tag 1','Tag 1', '7/23/2015','1')
INSERT INTO Tags(Name,Description,CreatedDate,UserId) VALUES ('Tag 2','Tag 2', '7/23/2015','1')
INSERT INTO Tags(Name,Description,CreatedDate,UserId) VALUES ('Tag 3','Tag 3', '7/23/2015','1')
INSERT INTO Tags(Name,Description,CreatedDate,UserId) VALUES ('Tag 4','Tag 4', '7/23/2015','1')
INSERT INTO Tags(Name,Description,CreatedDate,UserId) VALUES ('Tag 5','Tag 5', '7/23/2015','1')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('1','286')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('1','287')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('1','288')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('2','289')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('2','290')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('2','291')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('2','292')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('2','293')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('2','294')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('2','295')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('2','296')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('2','297')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('3','298')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('3','299')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('3','300')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('3','301')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('3','302')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('3','303')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('3','304')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('3','305')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('4','306')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('4','307')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('4','308')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('4','309')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('4','310')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('4','311')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('4','312')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('4','313')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('5','314')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('5','315')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('5','316')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('5','317')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('5','318')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('5','319')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('5','320')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('5','321')
INSERT INTO TagMainPost(Tags_Id,MainPosts_Id) VALUES ('5','322')
