//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public System.DateTime LastSeenInvitation { get; set; }
        public System.DateTime LastSeenSubcription { get; set; }
        public System.DateTime LastSeenNotification { get; set; }
        public System.DateTime LastLogin { get; set; }
        public string LastIp { get; set; }
        public System.DateTime LastSeenFriendRequest { get; set; }
    
        public virtual User User { get; set; }
    }
}
