//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article : MainPost
    {
        public int GroupId { get; set; }
        public Nullable<System.DateTime> PublicDate { get; set; }
        public Nullable<int> SeriesId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Series Series { get; set; }
    }
}
