//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanAccount
    {
        public BanAccount()
        {
            this.BanReasons = new HashSet<BanReason>();
        }
    
        public int Id { get; set; }
        public System.DateTime BannedDate { get; set; }
        public int Duration { get; set; }
        public System.DateTime UnBanedDate { get; set; }
        public int BannedUserId { get; set; }
        public int BanUserId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<BanReason> BanReasons { get; set; }
        public virtual User BannedUser { get; set; }
        public virtual User BanUser { get; set; }
    }
}
