//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanReason
    {
        public BanReason()
        {
            this.BanAccounts = new HashSet<BanAccount>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Duration { get; set; }
    
        public virtual ICollection<BanAccount> BanAccounts { get; set; }
    }
}
