//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CPMathHubModelContainer : DbContext
    {
        public CPMathHubModelContainer()
            : base("name=CPMathHubModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Invitation> Invitations { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<Privilege> Privileges { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Conversation> Conversations { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<UserFriendship> UserFriendships { get; set; }
        public virtual DbSet<PrivacySetting> PrivacySettings { get; set; }
        public virtual DbSet<EditedLog> EditedLogs { get; set; }
        public virtual DbSet<Participation> Participations { get; set; }
        public virtual DbSet<ReputationRule> ReputationRules { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Advertisement> Advertisements { get; set; }
        public virtual DbSet<BanAccount> BanAccounts { get; set; }
        public virtual DbSet<BanReason> BanReasons { get; set; }
        public virtual DbSet<Series> Series { get; set; }
        public virtual DbSet<ProfileHistory> ProfileHistories { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
    }
}
