//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    
    public enum EducationEnum : int
    {
        PrimarySchool = 1,
        SecondarySchool = 2,
        HighSchool = 3,
        Student = 4,
        Bachelor = 5,
        Master = 6,
        Doctor = 7,
        Professor = 8
    }
}
