//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Participations = new HashSet<Participation>();
            this.Series = new HashSet<Series>();
            this.Subscribers = new HashSet<User>();
            this.Articles = new HashSet<Article>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public GroupTypeEnum Type { get; set; }
    
        public virtual ICollection<Participation> Participations { get; set; }
        public virtual ICollection<Series> Series { get; set; }
        public virtual ICollection<User> Subscribers { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
    }
}
