//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation
    {
        public int Id { get; set; }
        public string InvitedDate { get; set; }
        public int MainPostId { get; set; }
        public int UserId { get; set; }
    
        public virtual MainPost MainPost { get; set; }
        public virtual User User { get; set; }
    }
}
