//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.ChildrenLocations = new HashSet<Location>();
            this.Profiles = new HashSet<Profile>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ZipCode { get; set; }
        public int ParentId { get; set; }
    
        public virtual ICollection<Location> ChildrenLocations { get; set; }
        public virtual Location ParentLocation { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
    }
}
