//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class MainPost : Post
    {
        public MainPost()
        {
            this.Tags = new HashSet<Tag>();
            this.BookmarkUsers = new HashSet<User>();
            this.FollowUsers = new HashSet<User>();
            this.Invitations = new HashSet<Invitation>();
            this.Sharers = new HashSet<User>();
        }
    
        public string Title { get; set; }
        public int View { get; set; }
        public MainPostPrivacyEnum Privacy { get; set; }
        public System.DateTime LastViewed { get; set; }
    
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<User> BookmarkUsers { get; set; }
        public virtual ICollection<User> FollowUsers { get; set; }
        public virtual ICollection<Invitation> Invitations { get; set; }
        public virtual ICollection<User> Sharers { get; set; }
    }
}
