//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    
    public enum NotificationEnum : int
    {
        UserAnswerQuestion = 1,
        UserCommentMainPost = 2,
        Invited = 3,
        UserComment = 4,
        AcceptedAnswer = 5,
        UserLikeComment = 6,
        ReceivedPrivilege = 7,
        Banned = 8,
        BlockedPost = 9,
        Voted = 10,
        SettedRole = 11
    }
}
