//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    
    public enum NotificationEnum : int
    {
        UserAnswerQuestion = 1,
        UserCommentMainPost = 2,
        Invited = 4,
        UserComment = 8,
        AcceptedAnswer = 16,
        UserLikeComment = 32,
        ReceivedPrivilege = 64,
        Banned = 128,
        BlockedPost = 256,
        Voted = 512,
        SettedRole = 1024
    }
}
