//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    
    public enum ParticipationEnum : int
    {
        Active = 1,
        Banned = 2,
        WaitingAccepted = 3,
        WaitingJoined = 4
    }
}
