//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
            this.Votes = new HashSet<Vote>();
            this.EditedContents = new HashSet<EditedContent>();
        }
    
        public int Id { get; set; }
        public string Content { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastEditedDate { get; set; }
        public int UserId { get; set; }
        public int Status { get; set; }
    
        public virtual User Author { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
        public virtual ICollection<EditedContent> EditedContents { get; set; }
    }
}
