//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivacySetting
    {
        public int Id { get; set; }
        public bool ReceiveEmail { get; set; }
        public FriendRequestEnum SendRequest { get; set; }
        public SeenBlogEnum SeenBlog { get; set; }
        public int Notification { get; set; }
    
        public virtual User User { get; set; }
    }
}
