//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilege
    {
        public Privilege()
        {
            this.Functions = new HashSet<Function>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Score { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
    
        public virtual ICollection<Function> Functions { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
