//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question : MainPost
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
    
        public virtual ICollection<Answer> Answers { get; set; }
    }
}
