//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    
    public enum ReportTypeEnum : int
    {
        DuplicateQuestion = 1,
        Swearing = 2,
        SpamComment = 3,
        Other = 0,
        SpamAnswer = 4,
        ClonedAccount = 5,
        SpamQuestion = 6,
        WrongMainPostPosition = 7
    }
}
