//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReputationRule
    {
        public int Id { get; set; }
        public int CommentLike { get; set; }
        public int QuestionUpVote { get; set; }
        public int QuestionDownVote { get; set; }
        public int DiscussionLike { get; set; }
        public int ArticleLike { get; set; }
        public int AnswerUpVote { get; set; }
        public int AnswerDownVote { get; set; }
        public int AcceptedAnswer { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
