//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.MainPosts = new HashSet<MainPost>();
            this.FavoriteUsers = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<MainPost> MainPosts { get; set; }
        public virtual ICollection<User> FavoriteUsers { get; set; }
        public virtual User Creator { get; set; }
    }
}
