//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_MathHub.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Posts = new HashSet<Post>();
            this.FavoriteTags = new HashSet<Tag>();
            this.Tags = new HashSet<Tag>();
            this.Bookmarks = new HashSet<MainPost>();
            this.FollowPosts = new HashSet<MainPost>();
            this.InviteInvitations = new HashSet<Invitation>();
            this.Votes = new HashSet<Vote>();
            this.Assessments = new HashSet<Accessment>();
            this.Privileges = new HashSet<Privilege>();
            this.Attendances = new HashSet<Attendance>();
            this.SharedMainPosts = new HashSet<MainPost>();
            this.ActiveRelationships = new HashSet<UserFriendship>();
            this.PassiveRelationship = new HashSet<UserFriendship>();
            this.Notifications = new HashSet<Notification>();
            this.GroupParticipations = new HashSet<Participation>();
            this.Reports = new HashSet<Report>();
            this.ReportedList = new HashSet<Report>();
            this.BannedAccounts = new HashSet<BanAccount>();
            this.BanAccounts = new HashSet<BanAccount>();
            this.EditedContents = new HashSet<EditedLog>();
            this.ProfileHistories = new HashSet<ProfileHistory>();
            this.SubscribedGroups = new HashSet<Group>();
            this.Followers = new HashSet<User>();
            this.Followees = new HashSet<User>();
            this.InvitedInvitations = new HashSet<Invitation>();
            this.UserClaims = new HashSet<UserClaim>();
            this.UserLogins = new HashSet<UserLogin>();
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string Email { get; set; }
        public Nullable<int> Reputation { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<UserStatusEnum> Status { get; set; }
        public bool EmailConfirmed { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual ICollection<Tag> FavoriteTags { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<MainPost> Bookmarks { get; set; }
        public virtual ICollection<MainPost> FollowPosts { get; set; }
        public virtual ICollection<Invitation> InviteInvitations { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
        public virtual ICollection<Accessment> Assessments { get; set; }
        public virtual ICollection<Privilege> Privileges { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<MainPost> SharedMainPosts { get; set; }
        public virtual ICollection<UserFriendship> ActiveRelationships { get; set; }
        public virtual ICollection<UserFriendship> PassiveRelationship { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual PrivacySetting PrivacySetting { get; set; }
        public virtual ICollection<Participation> GroupParticipations { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
        public virtual Image Avatar { get; set; }
        public virtual ICollection<Report> ReportedList { get; set; }
        public virtual ICollection<BanAccount> BannedAccounts { get; set; }
        public virtual ICollection<BanAccount> BanAccounts { get; set; }
        public virtual ICollection<EditedLog> EditedContents { get; set; }
        public virtual ICollection<ProfileHistory> ProfileHistories { get; set; }
        public virtual ICollection<Group> SubscribedGroups { get; set; }
        public virtual ICollection<User> Followers { get; set; }
        public virtual ICollection<User> Followees { get; set; }
        public virtual ICollection<Invitation> InvitedInvitations { get; set; }
        public virtual ICollection<UserClaim> UserClaims { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
        public virtual Activity Activity { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
